export const data = {
  "😀": "grinning face",
  "😃": "grinning face with big eyes",
  "😄": "grinning face with smiling eyes",
  "😁": "beaming face with smiling eyes",
  "😆": "grinning squinting face",
  "😅": "grinning face with sweat",
  "🤣": "rolling on the floor laughing",
  "😂": "face with tears of joy",
  "🙂": "slightly smiling face",
  "🙃": "upside-down face",
  "😉": "winking face",
  "😊": "smiling face with smiling eyes",
  "😇": "smiling face with halo",
  "🥰": "smiling face with hearts",
  "😍": "smiling face with heart-eyes",
  "🤩": "star-struck",
  "😘": "face blowing a kiss",
  "😗": "kissing face",
  "😚": "kissing face with closed eyes",
  "😙": "kissing face with smiling eyes",
  "😋": "face savoring food",
  "😛": "face with tongue",
  "😜": "winking face with tongue",
  "🤪": "zany face",
  "😝": "squinting face with tongue",
  "🤑": "money-mouth face",
  "🤗": "hugging face",
  "🤭": "face with hand over mouth",
  "🤫": "shushing face",
  "🤔": "thinking face",
  "🤐": "zipper-mouth face",
  "🤨": "face with raised eyebrow",
  "😐": "neutral face",
  "😑": "expressionless face",
  "😶": "face without mouth",
  "😏": "smirking face",
  "😒": "unamused face",
  "🙄": "face with rolling eyes",
  "😬": "grimacing face",
  "🤥": "lying face",
  "😌": "relieved face",
  "😔": "pensive face",
  "😪": "sleepy face",
  "🤤": "drooling face",
  "😴": "sleeping face",
  "😷": "face with medical mask",
  "🤒": "face with thermometer",
  "🤕": "face with head-bandage",
  "🤢": "nauseated face",
  "🤮": "face vomiting",
  "🤧": "sneezing face",
  "🥵": "hot face",
  "🥶": "cold face",
  "🥴": "woozy face",
  "😵": "knocked-out face",
  "🤯": "exploding head",
  "🤠": "cowboy hat face",
  "🥳": "partying face",
  "😎": "smiling face with sunglasses",
  "🤓": "nerd face",
  "🧐": "face with monocle",
  "😕": "confused face",
  "😟": "worried face",
  "🙁": "slightly frowning face",
  "☹️": "frowning face",
  "☹": "frowning face",
  "😮": "face with open mouth",
  "😯": "hushed face",
  "😲": "astonished face",
  "😳": "flushed face",
  "🥺": "pleading face",
  "😦": "frowning face with open mouth",
  "😧": "anguished face",
  "😨": "fearful face",
  "😰": "anxious face with sweat",
  "😥": "sad but relieved face",
  "😢": "crying face",
  "😭": "loudly crying face",
  "😱": "face screaming in fear",
  "😖": "confounded face",
  "😣": "persevering face",
  "😞": "disappointed face",
  "😓": "downcast face with sweat",
  "😩": "weary face",
  "😫": "tired face",
  "🥱": "yawning face",
  "😤": "face with steam from nose",
  "😡": "pouting face",
  "😠": "angry face",
  "🤬": "face with symbols on mouth",
  "😈": "smiling face with horns",
  "👿": "angry face with horns",
  "💀": "skull",
  "☠️": "skull and crossbones",
  "☠": "skull and crossbones",
  "💩": "pile of poo",
  "🤡": "clown face",
  "👹": "ogre",
  "👺": "goblin",
  "👻": "ghost",
  "👽": "alien",
  "👾": "alien monster",
  "🤖": "robot",
  "😺": "grinning cat",
  "😸": "grinning cat with smiling eyes",
  "😹": "cat with tears of joy",
  "😻": "smiling cat with heart-eyes",
  "😼": "cat with wry smile",
  "😽": "kissing cat",
  "🙀": "weary cat",
  "😿": "crying cat",
  "😾": "pouting cat",
  "🙈": "see-no-evil monkey",
  "🙉": "hear-no-evil monkey",
  "🙊": "speak-no-evil monkey",
  "💋": "kiss mark",
  "💌": "love letter",
  "💘": "heart with arrow",
  "💝": "heart with ribbon",
  "💖": "sparkling heart",
  "💗": "growing heart",
  "💓": "beating heart",
  "💞": "revolving hearts",
  "💕": "two hearts",
  "💟": "heart decoration",
  "❣️": "heart exclamation",
  "❣": "heart exclamation",
  "💔": "broken heart",
  "❤️": "red heart",
  "❤": "red heart",
  "🧡": "orange heart",
  "💛": "yellow heart",
  "💚": "green heart",
  "💙": "blue heart",
  "💜": "purple heart",
  "🤎": "brown heart",
  "🖤": "black heart",
  "🤍": "white heart",
  "💯": "hundred points",
  "💢": "anger symbol",
  "💥": "collision",
  "💫": "dizzy",
  "💦": "sweat droplets",
  "💨": "dashing away",
  "🕳️": "hole",
  "🕳": "hole",
  "💣": "bomb",
  "💬": "speech balloon",
  "👁️‍🗨️": "eye in speech bubble",
  "👁‍🗨️": "eye in speech bubble",
  "👁️‍🗨": "eye in speech bubble",
  "👁‍🗨": "eye in speech bubble",
  "🗨️": "left speech bubble",
  "🗨": "left speech bubble",
  "🗯️": "right anger bubble",
  "🗯": "right anger bubble",
  "💭": "thought balloon",
  "💤": "zzz",
  "👋": "waving hand",
  "👋🏻": "waving hand: light skin tone",
  "👋🏼": "waving hand: medium-light skin tone",
  "👋🏽": "waving hand: medium skin tone",
  "👋🏾": "waving hand: medium-dark skin tone",
  "👋🏿": "waving hand: dark skin tone",
  "🤚": "raised back of hand",
  "🤚🏻": "raised back of hand: light skin tone",
  "🤚🏼": "raised back of hand: medium-light skin tone",
  "🤚🏽": "raised back of hand: medium skin tone",
  "🤚🏾": "raised back of hand: medium-dark skin tone",
  "🤚🏿": "raised back of hand: dark skin tone",
  "🖐️": "hand with fingers splayed",
  "🖐": "hand with fingers splayed",
  "🖐🏻": "hand with fingers splayed: light skin tone",
  "🖐🏼": "hand with fingers splayed: medium-light skin tone",
  "🖐🏽": "hand with fingers splayed: medium skin tone",
  "🖐🏾": "hand with fingers splayed: medium-dark skin tone",
  "🖐🏿": "hand with fingers splayed: dark skin tone",
  "✋": "raised hand",
  "✋🏻": "raised hand: light skin tone",
  "✋🏼": "raised hand: medium-light skin tone",
  "✋🏽": "raised hand: medium skin tone",
  "✋🏾": "raised hand: medium-dark skin tone",
  "✋🏿": "raised hand: dark skin tone",
  "🖖": "vulcan salute",
  "🖖🏻": "vulcan salute: light skin tone",
  "🖖🏼": "vulcan salute: medium-light skin tone",
  "🖖🏽": "vulcan salute: medium skin tone",
  "🖖🏾": "vulcan salute: medium-dark skin tone",
  "🖖🏿": "vulcan salute: dark skin tone",
  "👌": "OK hand",
  "👌🏻": "OK hand: light skin tone",
  "👌🏼": "OK hand: medium-light skin tone",
  "👌🏽": "OK hand: medium skin tone",
  "👌🏾": "OK hand: medium-dark skin tone",
  "👌🏿": "OK hand: dark skin tone",
  "🤏": "pinching hand",
  "🤏🏻": "pinching hand: light skin tone",
  "🤏🏼": "pinching hand: medium-light skin tone",
  "🤏🏽": "pinching hand: medium skin tone",
  "🤏🏾": "pinching hand: medium-dark skin tone",
  "🤏🏿": "pinching hand: dark skin tone",
  "✌️": "victory hand",
  "✌": "victory hand",
  "✌🏻": "victory hand: light skin tone",
  "✌🏼": "victory hand: medium-light skin tone",
  "✌🏽": "victory hand: medium skin tone",
  "✌🏾": "victory hand: medium-dark skin tone",
  "✌🏿": "victory hand: dark skin tone",
  "🤞": "crossed fingers",
  "🤞🏻": "crossed fingers: light skin tone",
  "🤞🏼": "crossed fingers: medium-light skin tone",
  "🤞🏽": "crossed fingers: medium skin tone",
  "🤞🏾": "crossed fingers: medium-dark skin tone",
  "🤞🏿": "crossed fingers: dark skin tone",
  "🤟": "love-you gesture",
  "🤟🏻": "love-you gesture: light skin tone",
  "🤟🏼": "love-you gesture: medium-light skin tone",
  "🤟🏽": "love-you gesture: medium skin tone",
  "🤟🏾": "love-you gesture: medium-dark skin tone",
  "🤟🏿": "love-you gesture: dark skin tone",
  "🤘": "sign of the horns",
  "🤘🏻": "sign of the horns: light skin tone",
  "🤘🏼": "sign of the horns: medium-light skin tone",
  "🤘🏽": "sign of the horns: medium skin tone",
  "🤘🏾": "sign of the horns: medium-dark skin tone",
  "🤘🏿": "sign of the horns: dark skin tone",
  "🤙": "call me hand",
  "🤙🏻": "call me hand: light skin tone",
  "🤙🏼": "call me hand: medium-light skin tone",
  "🤙🏽": "call me hand: medium skin tone",
  "🤙🏾": "call me hand: medium-dark skin tone",
  "🤙🏿": "call me hand: dark skin tone",
  "👈": "backhand index pointing left",
  "👈🏻": "backhand index pointing left: light skin tone",
  "👈🏼": "backhand index pointing left: medium-light skin tone",
  "👈🏽": "backhand index pointing left: medium skin tone",
  "👈🏾": "backhand index pointing left: medium-dark skin tone",
  "👈🏿": "backhand index pointing left: dark skin tone",
  "👉": "backhand index pointing right",
  "👉🏻": "backhand index pointing right: light skin tone",
  "👉🏼": "backhand index pointing right: medium-light skin tone",
  "👉🏽": "backhand index pointing right: medium skin tone",
  "👉🏾": "backhand index pointing right: medium-dark skin tone",
  "👉🏿": "backhand index pointing right: dark skin tone",
  "👆": "backhand index pointing up",
  "👆🏻": "backhand index pointing up: light skin tone",
  "👆🏼": "backhand index pointing up: medium-light skin tone",
  "👆🏽": "backhand index pointing up: medium skin tone",
  "👆🏾": "backhand index pointing up: medium-dark skin tone",
  "👆🏿": "backhand index pointing up: dark skin tone",
  "👇": "backhand index pointing down",
  "👇🏻": "backhand index pointing down: light skin tone",
  "👇🏼": "backhand index pointing down: medium-light skin tone",
  "👇🏽": "backhand index pointing down: medium skin tone",
  "👇🏾": "backhand index pointing down: medium-dark skin tone",
  "👇🏿": "backhand index pointing down: dark skin tone",
  "☝️": "index pointing up",
  "☝": "index pointing up",
  "☝🏻": "index pointing up: light skin tone",
  "☝🏼": "index pointing up: medium-light skin tone",
  "☝🏽": "index pointing up: medium skin tone",
  "☝🏾": "index pointing up: medium-dark skin tone",
  "☝🏿": "index pointing up: dark skin tone",
  "👍": "thumbs up",
  "👍🏻": "thumbs up: light skin tone",
  "👍🏼": "thumbs up: medium-light skin tone",
  "👍🏽": "thumbs up: medium skin tone",
  "👍🏾": "thumbs up: medium-dark skin tone",
  "👍🏿": "thumbs up: dark skin tone",
  "👎": "thumbs down",
  "👎🏻": "thumbs down: light skin tone",
  "👎🏼": "thumbs down: medium-light skin tone",
  "👎🏽": "thumbs down: medium skin tone",
  "👎🏾": "thumbs down: medium-dark skin tone",
  "👎🏿": "thumbs down: dark skin tone",
  "✊": "raised fist",
  "✊🏻": "raised fist: light skin tone",
  "✊🏼": "raised fist: medium-light skin tone",
  "✊🏽": "raised fist: medium skin tone",
  "✊🏾": "raised fist: medium-dark skin tone",
  "✊🏿": "raised fist: dark skin tone",
  "👊": "oncoming fist",
  "👊🏻": "oncoming fist: light skin tone",
  "👊🏼": "oncoming fist: medium-light skin tone",
  "👊🏽": "oncoming fist: medium skin tone",
  "👊🏾": "oncoming fist: medium-dark skin tone",
  "👊🏿": "oncoming fist: dark skin tone",
  "🤛": "left-facing fist",
  "🤛🏻": "left-facing fist: light skin tone",
  "🤛🏼": "left-facing fist: medium-light skin tone",
  "🤛🏽": "left-facing fist: medium skin tone",
  "🤛🏾": "left-facing fist: medium-dark skin tone",
  "🤛🏿": "left-facing fist: dark skin tone",
  "🤜": "right-facing fist",
  "🤜🏻": "right-facing fist: light skin tone",
  "🤜🏼": "right-facing fist: medium-light skin tone",
  "🤜🏽": "right-facing fist: medium skin tone",
  "🤜🏾": "right-facing fist: medium-dark skin tone",
  "🤜🏿": "right-facing fist: dark skin tone",
  "👏": "clapping hands",
  "👏🏻": "clapping hands: light skin tone",
  "👏🏼": "clapping hands: medium-light skin tone",
  "👏🏽": "clapping hands: medium skin tone",
  "👏🏾": "clapping hands: medium-dark skin tone",
  "👏🏿": "clapping hands: dark skin tone",
  "🙌": "raising hands",
  "🙌🏻": "raising hands: light skin tone",
  "🙌🏼": "raising hands: medium-light skin tone",
  "🙌🏽": "raising hands: medium skin tone",
  "🙌🏾": "raising hands: medium-dark skin tone",
  "🙌🏿": "raising hands: dark skin tone",
  "👐": "open hands",
  "👐🏻": "open hands: light skin tone",
  "👐🏼": "open hands: medium-light skin tone",
  "👐🏽": "open hands: medium skin tone",
  "👐🏾": "open hands: medium-dark skin tone",
  "👐🏿": "open hands: dark skin tone",
  "🤲": "palms up together",
  "🤲🏻": "palms up together: light skin tone",
  "🤲🏼": "palms up together: medium-light skin tone",
  "🤲🏽": "palms up together: medium skin tone",
  "🤲🏾": "palms up together: medium-dark skin tone",
  "🤲🏿": "palms up together: dark skin tone",
  "🤝": "handshake",
  "🙏": "folded hands",
  "🙏🏻": "folded hands: light skin tone",
  "🙏🏼": "folded hands: medium-light skin tone",
  "🙏🏽": "folded hands: medium skin tone",
  "🙏🏾": "folded hands: medium-dark skin tone",
  "🙏🏿": "folded hands: dark skin tone",
  "✍️": "writing hand",
  "✍": "writing hand",
  "✍🏻": "writing hand: light skin tone",
  "✍🏼": "writing hand: medium-light skin tone",
  "✍🏽": "writing hand: medium skin tone",
  "✍🏾": "writing hand: medium-dark skin tone",
  "✍🏿": "writing hand: dark skin tone",
  "💅": "nail polish",
  "💅🏻": "nail polish: light skin tone",
  "💅🏼": "nail polish: medium-light skin tone",
  "💅🏽": "nail polish: medium skin tone",
  "💅🏾": "nail polish: medium-dark skin tone",
  "💅🏿": "nail polish: dark skin tone",
  "🤳": "selfie",
  "🤳🏻": "selfie: light skin tone",
  "🤳🏼": "selfie: medium-light skin tone",
  "🤳🏽": "selfie: medium skin tone",
  "🤳🏾": "selfie: medium-dark skin tone",
  "🤳🏿": "selfie: dark skin tone",
  "💪": "flexed biceps",
  "💪🏻": "flexed biceps: light skin tone",
  "💪🏼": "flexed biceps: medium-light skin tone",
  "💪🏽": "flexed biceps: medium skin tone",
  "💪🏾": "flexed biceps: medium-dark skin tone",
  "💪🏿": "flexed biceps: dark skin tone",
  "🦾": "mechanical arm",
  "🦿": "mechanical leg",
  "🦵": "leg",
  "🦵🏻": "leg: light skin tone",
  "🦵🏼": "leg: medium-light skin tone",
  "🦵🏽": "leg: medium skin tone",
  "🦵🏾": "leg: medium-dark skin tone",
  "🦵🏿": "leg: dark skin tone",
  "🦶": "foot",
  "🦶🏻": "foot: light skin tone",
  "🦶🏼": "foot: medium-light skin tone",
  "🦶🏽": "foot: medium skin tone",
  "🦶🏾": "foot: medium-dark skin tone",
  "🦶🏿": "foot: dark skin tone",
  "👂": "ear",
  "👂🏻": "ear: light skin tone",
  "👂🏼": "ear: medium-light skin tone",
  "👂🏽": "ear: medium skin tone",
  "👂🏾": "ear: medium-dark skin tone",
  "👂🏿": "ear: dark skin tone",
  "🦻": "ear with hearing aid",
  "🦻🏻": "ear with hearing aid: light skin tone",
  "🦻🏼": "ear with hearing aid: medium-light skin tone",
  "🦻🏽": "ear with hearing aid: medium skin tone",
  "🦻🏾": "ear with hearing aid: medium-dark skin tone",
  "🦻🏿": "ear with hearing aid: dark skin tone",
  "👃": "nose",
  "👃🏻": "nose: light skin tone",
  "👃🏼": "nose: medium-light skin tone",
  "👃🏽": "nose: medium skin tone",
  "👃🏾": "nose: medium-dark skin tone",
  "👃🏿": "nose: dark skin tone",
  "🧠": "brain",
  "🫀": "anatomical heart",
  "🫁": "lungs",
  "🦷": "tooth",
  "🦴": "bone",
  "👀": "eyes",
  "👁️": "eye",
  "👁": "eye",
  "👅": "tongue",
  "👄": "mouth",
  "👶": "baby",
  "👶🏻": "baby: light skin tone",
  "👶🏼": "baby: medium-light skin tone",
  "👶🏽": "baby: medium skin tone",
  "👶🏾": "baby: medium-dark skin tone",
  "👶🏿": "baby: dark skin tone",
  "🧒": "child",
  "🧒🏻": "child: light skin tone",
  "🧒🏼": "child: medium-light skin tone",
  "🧒🏽": "child: medium skin tone",
  "🧒🏾": "child: medium-dark skin tone",
  "🧒🏿": "child: dark skin tone",
  "👦": "boy",
  "👦🏻": "boy: light skin tone",
  "👦🏼": "boy: medium-light skin tone",
  "👦🏽": "boy: medium skin tone",
  "👦🏾": "boy: medium-dark skin tone",
  "👦🏿": "boy: dark skin tone",
  "👧": "girl",
  "👧🏻": "girl: light skin tone",
  "👧🏼": "girl: medium-light skin tone",
  "👧🏽": "girl: medium skin tone",
  "👧🏾": "girl: medium-dark skin tone",
  "👧🏿": "girl: dark skin tone",
  "🧑": "person",
  "🧑🏻": "person: light skin tone",
  "🧑🏼": "person: medium-light skin tone",
  "🧑🏽": "person: medium skin tone",
  "🧑🏾": "person: medium-dark skin tone",
  "🧑🏿": "person: dark skin tone",
  "👱": "person: blond hair",
  "👱🏻": "person: light skin tone, blond hair",
  "👱🏼": "person: medium-light skin tone, blond hair",
  "👱🏽": "person: medium skin tone, blond hair",
  "👱🏾": "person: medium-dark skin tone, blond hair",
  "👱🏿": "person: dark skin tone, blond hair",
  "👨": "man",
  "👨🏻": "man: light skin tone",
  "👨🏼": "man: medium-light skin tone",
  "👨🏽": "man: medium skin tone",
  "👨🏾": "man: medium-dark skin tone",
  "👨🏿": "man: dark skin tone",
  "🧔": "person: beard",
  "🧔🏻": "person: light skin tone, beard",
  "🧔🏼": "person: medium-light skin tone, beard",
  "🧔🏽": "person: medium skin tone, beard",
  "🧔🏾": "person: medium-dark skin tone, beard",
  "🧔🏿": "person: dark skin tone, beard",
  "👨‍🦰": "man: red hair",
  "👨🏻‍🦰": "man: light skin tone, red hair",
  "👨🏼‍🦰": "man: medium-light skin tone, red hair",
  "👨🏽‍🦰": "man: medium skin tone, red hair",
  "👨🏾‍🦰": "man: medium-dark skin tone, red hair",
  "👨🏿‍🦰": "man: dark skin tone, red hair",
  "👨‍🦱": "man: curly hair",
  "👨🏻‍🦱": "man: light skin tone, curly hair",
  "👨🏼‍🦱": "man: medium-light skin tone, curly hair",
  "👨🏽‍🦱": "man: medium skin tone, curly hair",
  "👨🏾‍🦱": "man: medium-dark skin tone, curly hair",
  "👨🏿‍🦱": "man: dark skin tone, curly hair",
  "👨‍🦳": "man: white hair",
  "👨🏻‍🦳": "man: light skin tone, white hair",
  "👨🏼‍🦳": "man: medium-light skin tone, white hair",
  "👨🏽‍🦳": "man: medium skin tone, white hair",
  "👨🏾‍🦳": "man: medium-dark skin tone, white hair",
  "👨🏿‍🦳": "man: dark skin tone, white hair",
  "👨‍🦲": "man: bald",
  "👨🏻‍🦲": "man: light skin tone, bald",
  "👨🏼‍🦲": "man: medium-light skin tone, bald",
  "👨🏽‍🦲": "man: medium skin tone, bald",
  "👨🏾‍🦲": "man: medium-dark skin tone, bald",
  "👨🏿‍🦲": "man: dark skin tone, bald",
  "👩": "woman",
  "👩🏻": "woman: light skin tone",
  "👩🏼": "woman: medium-light skin tone",
  "👩🏽": "woman: medium skin tone",
  "👩🏾": "woman: medium-dark skin tone",
  "👩🏿": "woman: dark skin tone",
  "👩‍🦰": "woman: red hair",
  "👩🏻‍🦰": "woman: light skin tone, red hair",
  "👩🏼‍🦰": "woman: medium-light skin tone, red hair",
  "👩🏽‍🦰": "woman: medium skin tone, red hair",
  "👩🏾‍🦰": "woman: medium-dark skin tone, red hair",
  "👩🏿‍🦰": "woman: dark skin tone, red hair",
  "👩‍🦱": "woman: curly hair",
  "👩🏻‍🦱": "woman: light skin tone, curly hair",
  "👩🏼‍🦱": "woman: medium-light skin tone, curly hair",
  "👩🏽‍🦱": "woman: medium skin tone, curly hair",
  "👩🏾‍🦱": "woman: medium-dark skin tone, curly hair",
  "👩🏿‍🦱": "woman: dark skin tone, curly hair",
  "👩‍🦳": "woman: white hair",
  "👩🏻‍🦳": "woman: light skin tone, white hair",
  "👩🏼‍🦳": "woman: medium-light skin tone, white hair",
  "👩🏽‍🦳": "woman: medium skin tone, white hair",
  "👩🏾‍🦳": "woman: medium-dark skin tone, white hair",
  "👩🏿‍🦳": "woman: dark skin tone, white hair",
  "👩‍🦲": "woman: bald",
  "👩🏻‍🦲": "woman: light skin tone, bald",
  "👩🏼‍🦲": "woman: medium-light skin tone, bald",
  "👩🏽‍🦲": "woman: medium skin tone, bald",
  "👩🏾‍🦲": "woman: medium-dark skin tone, bald",
  "👩🏿‍🦲": "woman: dark skin tone, bald",
  "👱‍♀": "woman: blond hair",
  "👱🏻‍♀️": "woman: light skin tone, blond hair",
  "👱🏻‍♀": "woman: light skin tone, blond hair",
  "👱🏼‍♀️": "woman: medium-light skin tone, blond hair",
  "👱🏼‍♀": "woman: medium-light skin tone, blond hair",
  "👱🏽‍♀️": "woman: medium skin tone, blond hair",
  "👱🏽‍♀": "woman: medium skin tone, blond hair",
  "👱🏾‍♀️": "woman: medium-dark skin tone, blond hair",
  "👱🏾‍♀": "woman: medium-dark skin tone, blond hair",
  "👱🏿‍♀️": "woman: dark skin tone, blond hair",
  "👱🏿‍♀": "woman: dark skin tone, blond hair",
  "👱‍♂️": "man: blond hair",
  "👱‍♂": "man: blond hair",
  "👱🏻‍♂️": "man: light skin tone, blond hair",
  "👱🏻‍♂": "man: light skin tone, blond hair",
  "👱🏼‍♂️": "man: medium-light skin tone, blond hair",
  "👱🏼‍♂": "man: medium-light skin tone, blond hair",
  "👱🏽‍♂️": "man: medium skin tone, blond hair",
  "👱🏽‍♂": "man: medium skin tone, blond hair",
  "👱🏾‍♂️": "man: medium-dark skin tone, blond hair",
  "👱🏾‍♂": "man: medium-dark skin tone, blond hair",
  "👱🏿‍♂️": "man: dark skin tone, blond hair",
  "👱🏿‍♂": "man: dark skin tone, blond hair",
  "🧓": "older person",
  "🧓🏻": "older person: light skin tone",
  "🧓🏼": "older person: medium-light skin tone",
  "🧓🏽": "older person: medium skin tone",
  "🧓🏾": "older person: medium-dark skin tone",
  "🧓🏿": "older person: dark skin tone",
  "👴": "old man",
  "👴🏻": "old man: light skin tone",
  "👴🏼": "old man: medium-light skin tone",
  "👴🏽": "old man: medium skin tone",
  "👴🏾": "old man: medium-dark skin tone",
  "👴🏿": "old man: dark skin tone",
  "👵": "old woman",
  "👵🏻": "old woman: light skin tone",
  "👵🏼": "old woman: medium-light skin tone",
  "👵🏽": "old woman: medium skin tone",
  "👵🏾": "old woman: medium-dark skin tone",
  "👵🏿": "old woman: dark skin tone",
  "🙍": "person frowning",
  "🙍🏻": "person frowning: light skin tone",
  "🙍🏼": "person frowning: medium-light skin tone",
  "🙍🏽": "person frowning: medium skin tone",
  "🙍🏾": "person frowning: medium-dark skin tone",
  "🙍🏿": "person frowning: dark skin tone",
  "🙍‍♂️": "man frowning",
  "🙍‍♂": "man frowning",
  "🙍🏻‍♂️": "man frowning: light skin tone",
  "🙍🏻‍♂": "man frowning: light skin tone",
  "🙍🏼‍♂️": "man frowning: medium-light skin tone",
  "🙍🏼‍♂": "man frowning: medium-light skin tone",
  "🙍🏽‍♂️": "man frowning: medium skin tone",
  "🙍🏽‍♂": "man frowning: medium skin tone",
  "🙍🏾‍♂️": "man frowning: medium-dark skin tone",
  "🙍🏾‍♂": "man frowning: medium-dark skin tone",
  "🙍🏿‍♂️": "man frowning: dark skin tone",
  "🙍🏿‍♂": "man frowning: dark skin tone",
  "🙍‍♀️": "woman frowning",
  "🙍‍♀": "woman frowning",
  "🙍🏻‍♀️": "woman frowning: light skin tone",
  "🙍🏻‍♀": "woman frowning: light skin tone",
  "🙍🏼‍♀️": "woman frowning: medium-light skin tone",
  "🙍🏼‍♀": "woman frowning: medium-light skin tone",
  "🙍🏽‍♀️": "woman frowning: medium skin tone",
  "🙍🏽‍♀": "woman frowning: medium skin tone",
  "🙍🏾‍♀️": "woman frowning: medium-dark skin tone",
  "🙍🏾‍♀": "woman frowning: medium-dark skin tone",
  "🙍🏿‍♀️": "woman frowning: dark skin tone",
  "🙍🏿‍♀": "woman frowning: dark skin tone",
  "🙎": "person pouting",
  "🙎🏻": "person pouting: light skin tone",
  "🙎🏼": "person pouting: medium-light skin tone",
  "🙎🏽": "person pouting: medium skin tone",
  "🙎🏾": "person pouting: medium-dark skin tone",
  "🙎🏿": "person pouting: dark skin tone",
  "🙎‍♂️": "man pouting",
  "🙎‍♂": "man pouting",
  "🙎🏻‍♂️": "man pouting: light skin tone",
  "🙎🏻‍♂": "man pouting: light skin tone",
  "🙎🏼‍♂️": "man pouting: medium-light skin tone",
  "🙎🏼‍♂": "man pouting: medium-light skin tone",
  "🙎🏽‍♂️": "man pouting: medium skin tone",
  "🙎🏽‍♂": "man pouting: medium skin tone",
  "🙎🏾‍♂️": "man pouting: medium-dark skin tone",
  "🙎🏾‍♂": "man pouting: medium-dark skin tone",
  "🙎🏿‍♂️": "man pouting: dark skin tone",
  "🙎🏿‍♂": "man pouting: dark skin tone",
  "🙎‍♀️": "woman pouting",
  "🙎‍♀": "woman pouting",
  "🙎🏻‍♀️": "woman pouting: light skin tone",
  "🙎🏻‍♀": "woman pouting: light skin tone",
  "🙎🏼‍♀️": "woman pouting: medium-light skin tone",
  "🙎🏼‍♀": "woman pouting: medium-light skin tone",
  "🙎🏽‍♀️": "woman pouting: medium skin tone",
  "🙎🏽‍♀": "woman pouting: medium skin tone",
  "🙎🏾‍♀️": "woman pouting: medium-dark skin tone",
  "🙎🏾‍♀": "woman pouting: medium-dark skin tone",
  "🙎🏿‍♀️": "woman pouting: dark skin tone",
  "🙎🏿‍♀": "woman pouting: dark skin tone",
  "🙅": "person gesturing NO",
  "🙅🏻": "person gesturing NO: light skin tone",
  "🙅🏼": "person gesturing NO: medium-light skin tone",
  "🙅🏽": "person gesturing NO: medium skin tone",
  "🙅🏾": "person gesturing NO: medium-dark skin tone",
  "🙅🏿": "person gesturing NO: dark skin tone",
  "🙅‍♂️": "man gesturing NO",
  "🙅‍♂": "man gesturing NO",
  "🙅🏻‍♂️": "man gesturing NO: light skin tone",
  "🙅🏻‍♂": "man gesturing NO: light skin tone",
  "🙅🏼‍♂️": "man gesturing NO: medium-light skin tone",
  "🙅🏼‍♂": "man gesturing NO: medium-light skin tone",
  "🙅🏽‍♂️": "man gesturing NO: medium skin tone",
  "🙅🏽‍♂": "man gesturing NO: medium skin tone",
  "🙅🏾‍♂️": "man gesturing NO: medium-dark skin tone",
  "🙅🏾‍♂": "man gesturing NO: medium-dark skin tone",
  "🙅🏿‍♂️": "man gesturing NO: dark skin tone",
  "🙅🏿‍♂": "man gesturing NO: dark skin tone",
  "🙅‍♀️": "woman gesturing NO",
  "🙅‍♀": "woman gesturing NO",
  "🙅🏻‍♀️": "woman gesturing NO: light skin tone",
  "🙅🏻‍♀": "woman gesturing NO: light skin tone",
  "🙅🏼‍♀️": "woman gesturing NO: medium-light skin tone",
  "🙅🏼‍♀": "woman gesturing NO: medium-light skin tone",
  "🙅🏽‍♀️": "woman gesturing NO: medium skin tone",
  "🙅🏽‍♀": "woman gesturing NO: medium skin tone",
  "🙅🏾‍♀️": "woman gesturing NO: medium-dark skin tone",
  "🙅🏾‍♀": "woman gesturing NO: medium-dark skin tone",
  "🙅🏿‍♀️": "woman gesturing NO: dark skin tone",
  "🙅🏿‍♀": "woman gesturing NO: dark skin tone",
  "🙆": "person gesturing OK",
  "🙆🏻": "person gesturing OK: light skin tone",
  "🙆🏼": "person gesturing OK: medium-light skin tone",
  "🙆🏽": "person gesturing OK: medium skin tone",
  "🙆🏾": "person gesturing OK: medium-dark skin tone",
  "🙆🏿": "person gesturing OK: dark skin tone",
  "🙆‍♂️": "man gesturing OK",
  "🙆‍♂": "man gesturing OK",
  "🙆🏻‍♂️": "man gesturing OK: light skin tone",
  "🙆🏻‍♂": "man gesturing OK: light skin tone",
  "🙆🏼‍♂️": "man gesturing OK: medium-light skin tone",
  "🙆🏼‍♂": "man gesturing OK: medium-light skin tone",
  "🙆🏽‍♂️": "man gesturing OK: medium skin tone",
  "🙆🏽‍♂": "man gesturing OK: medium skin tone",
  "🙆🏾‍♂️": "man gesturing OK: medium-dark skin tone",
  "🙆🏾‍♂": "man gesturing OK: medium-dark skin tone",
  "🙆🏿‍♂️": "man gesturing OK: dark skin tone",
  "🙆🏿‍♂": "man gesturing OK: dark skin tone",
  "🙆‍♀️": "woman gesturing OK",
  "🙆‍♀": "woman gesturing OK",
  "🙆🏻‍♀️": "woman gesturing OK: light skin tone",
  "🙆🏻‍♀": "woman gesturing OK: light skin tone",
  "🙆🏼‍♀️": "woman gesturing OK: medium-light skin tone",
  "🙆🏼‍♀": "woman gesturing OK: medium-light skin tone",
  "🙆🏽‍♀️": "woman gesturing OK: medium skin tone",
  "🙆🏽‍♀": "woman gesturing OK: medium skin tone",
  "🙆🏾‍♀️": "woman gesturing OK: medium-dark skin tone",
  "🙆🏾‍♀": "woman gesturing OK: medium-dark skin tone",
  "🙆🏿‍♀️": "woman gesturing OK: dark skin tone",
  "🙆🏿‍♀": "woman gesturing OK: dark skin tone",
  "💁": "person tipping hand",
  "💁🏻": "person tipping hand: light skin tone",
  "💁🏼": "person tipping hand: medium-light skin tone",
  "💁🏽": "person tipping hand: medium skin tone",
  "💁🏾": "person tipping hand: medium-dark skin tone",
  "💁🏿": "person tipping hand: dark skin tone",
  "💁‍♂️": "man tipping hand",
  "💁‍♂": "man tipping hand",
  "💁🏻‍♂️": "man tipping hand: light skin tone",
  "💁🏻‍♂": "man tipping hand: light skin tone",
  "💁🏼‍♂️": "man tipping hand: medium-light skin tone",
  "💁🏼‍♂": "man tipping hand: medium-light skin tone",
  "💁🏽‍♂️": "man tipping hand: medium skin tone",
  "💁🏽‍♂": "man tipping hand: medium skin tone",
  "💁🏾‍♂️": "man tipping hand: medium-dark skin tone",
  "💁🏾‍♂": "man tipping hand: medium-dark skin tone",
  "💁🏿‍♂️": "man tipping hand: dark skin tone",
  "💁🏿‍♂": "man tipping hand: dark skin tone",
  "💁‍♀️": "woman tipping hand",
  "💁‍♀": "woman tipping hand",
  "💁🏻‍♀️": "woman tipping hand: light skin tone",
  "💁🏻‍♀": "woman tipping hand: light skin tone",
  "💁🏼‍♀️": "woman tipping hand: medium-light skin tone",
  "💁🏼‍♀": "woman tipping hand: medium-light skin tone",
  "💁🏽‍♀️": "woman tipping hand: medium skin tone",
  "💁🏽‍♀": "woman tipping hand: medium skin tone",
  "💁🏾‍♀️": "woman tipping hand: medium-dark skin tone",
  "💁🏾‍♀": "woman tipping hand: medium-dark skin tone",
  "💁🏿‍♀️": "woman tipping hand: dark skin tone",
  "💁🏿‍♀": "woman tipping hand: dark skin tone",
  "🙋": "person raising hand",
  "🙋🏻": "person raising hand: light skin tone",
  "🙋🏼": "person raising hand: medium-light skin tone",
  "🙋🏽": "person raising hand: medium skin tone",
  "🙋🏾": "person raising hand: medium-dark skin tone",
  "🙋🏿": "person raising hand: dark skin tone",
  "🙋‍♂️": "man raising hand",
  "🙋‍♂": "man raising hand",
  "🙋🏻‍♂️": "man raising hand: light skin tone",
  "🙋🏻‍♂": "man raising hand: light skin tone",
  "🙋🏼‍♂️": "man raising hand: medium-light skin tone",
  "🙋🏼‍♂": "man raising hand: medium-light skin tone",
  "🙋🏽‍♂️": "man raising hand: medium skin tone",
  "🙋🏽‍♂": "man raising hand: medium skin tone",
  "🙋🏾‍♂️": "man raising hand: medium-dark skin tone",
  "🙋🏾‍♂": "man raising hand: medium-dark skin tone",
  "🙋🏿‍♂️": "man raising hand: dark skin tone",
  "🙋🏿‍♂": "man raising hand: dark skin tone",
  "🙋‍♀️": "woman raising hand",
  "🙋‍♀": "woman raising hand",
  "🙋🏻‍♀️": "woman raising hand: light skin tone",
  "🙋🏻‍♀": "woman raising hand: light skin tone",
  "🙋🏼‍♀️": "woman raising hand: medium-light skin tone",
  "🙋🏼‍♀": "woman raising hand: medium-light skin tone",
  "🙋🏽‍♀️": "woman raising hand: medium skin tone",
  "🙋🏽‍♀": "woman raising hand: medium skin tone",
  "🙋🏾‍♀️": "woman raising hand: medium-dark skin tone",
  "🙋🏾‍♀": "woman raising hand: medium-dark skin tone",
  "🙋🏿‍♀️": "woman raising hand: dark skin tone",
  "🙋🏿‍♀": "woman raising hand: dark skin tone",
  "🧏": "deaf person",
  "🧏🏻": "deaf person: light skin tone",
  "🧏🏼": "deaf person: medium-light skin tone",
  "🧏🏽": "deaf person: medium skin tone",
  "🧏🏾": "deaf person: medium-dark skin tone",
  "🧏🏿": "deaf person: dark skin tone",
  "🧏‍♂️": "deaf man",
  "🧏‍♂": "deaf man",
  "🧏🏻‍♂️": "deaf man: light skin tone",
  "🧏🏻‍♂": "deaf man: light skin tone",
  "🧏🏼‍♂️": "deaf man: medium-light skin tone",
  "🧏🏼‍♂": "deaf man: medium-light skin tone",
  "🧏🏽‍♂️": "deaf man: medium skin tone",
  "🧏🏽‍♂": "deaf man: medium skin tone",
  "🧏🏾‍♂️": "deaf man: medium-dark skin tone",
  "🧏🏾‍♂": "deaf man: medium-dark skin tone",
  "🧏🏿‍♂️": "deaf man: dark skin tone",
  "🧏🏿‍♂": "deaf man: dark skin tone",
  "🧏‍♀️": "deaf woman",
  "🧏‍♀": "deaf woman",
  "🧏🏻‍♀️": "deaf woman: light skin tone",
  "🧏🏻‍♀": "deaf woman: light skin tone",
  "🧏🏼‍♀️": "deaf woman: medium-light skin tone",
  "🧏🏼‍♀": "deaf woman: medium-light skin tone",
  "🧏🏽‍♀️": "deaf woman: medium skin tone",
  "🧏🏽‍♀": "deaf woman: medium skin tone",
  "🧏🏾‍♀️": "deaf woman: medium-dark skin tone",
  "🧏🏾‍♀": "deaf woman: medium-dark skin tone",
  "🧏🏿‍♀️": "deaf woman: dark skin tone",
  "🧏🏿‍♀": "deaf woman: dark skin tone",
  "🙇": "person bowing",
  "🙇🏻": "person bowing: light skin tone",
  "🙇🏼": "person bowing: medium-light skin tone",
  "🙇🏽": "person bowing: medium skin tone",
  "🙇🏾": "person bowing: medium-dark skin tone",
  "🙇🏿": "person bowing: dark skin tone",
  "🙇‍♂️": "man bowing",
  "🙇‍♂": "man bowing",
  "🙇🏻‍♂️": "man bowing: light skin tone",
  "🙇🏻‍♂": "man bowing: light skin tone",
  "🙇🏼‍♂️": "man bowing: medium-light skin tone",
  "🙇🏼‍♂": "man bowing: medium-light skin tone",
  "🙇🏽‍♂️": "man bowing: medium skin tone",
  "🙇🏽‍♂": "man bowing: medium skin tone",
  "🙇🏾‍♂️": "man bowing: medium-dark skin tone",
  "🙇🏾‍♂": "man bowing: medium-dark skin tone",
  "🙇🏿‍♂️": "man bowing: dark skin tone",
  "🙇🏿‍♂": "man bowing: dark skin tone",
  "🙇‍♀️": "woman bowing",
  "🙇‍♀": "woman bowing",
  "🙇🏻‍♀️": "woman bowing: light skin tone",
  "🙇🏻‍♀": "woman bowing: light skin tone",
  "🙇🏼‍♀️": "woman bowing: medium-light skin tone",
  "🙇🏼‍♀": "woman bowing: medium-light skin tone",
  "🙇🏽‍♀️": "woman bowing: medium skin tone",
  "🙇🏽‍♀": "woman bowing: medium skin tone",
  "🙇🏾‍♀️": "woman bowing: medium-dark skin tone",
  "🙇🏾‍♀": "woman bowing: medium-dark skin tone",
  "🙇🏿‍♀️": "woman bowing: dark skin tone",
  "🙇🏿‍♀": "woman bowing: dark skin tone",
  "🤦": "person facepalming",
  "🤦🏻": "person facepalming: light skin tone",
  "🤦🏼": "person facepalming: medium-light skin tone",
  "🤦🏽": "person facepalming: medium skin tone",
  "🤦🏾": "person facepalming: medium-dark skin tone",
  "🤦🏿": "person facepalming: dark skin tone",
  "🤦‍♂️": "man facepalming",
  "🤦‍♂": "man facepalming",
  "🤦🏻‍♂️": "man facepalming: light skin tone",
  "🤦🏻‍♂": "man facepalming: light skin tone",
  "🤦🏼‍♂️": "man facepalming: medium-light skin tone",
  "🤦🏼‍♂": "man facepalming: medium-light skin tone",
  "🤦🏽‍♂️": "man facepalming: medium skin tone",
  "🤦🏽‍♂": "man facepalming: medium skin tone",
  "🤦🏾‍♂️": "man facepalming: medium-dark skin tone",
  "🤦🏾‍♂": "man facepalming: medium-dark skin tone",
  "🤦🏿‍♂️": "man facepalming: dark skin tone",
  "🤦🏿‍♂": "man facepalming: dark skin tone",
  "🤦‍♀️": "woman facepalming",
  "🤦‍♀": "woman facepalming",
  "🤦🏻‍♀️": "woman facepalming: light skin tone",
  "🤦🏻‍♀": "woman facepalming: light skin tone",
  "🤦🏼‍♀️": "woman facepalming: medium-light skin tone",
  "🤦🏼‍♀": "woman facepalming: medium-light skin tone",
  "🤦🏽‍♀️": "woman facepalming: medium skin tone",
  "🤦🏽‍♀": "woman facepalming: medium skin tone",
  "🤦🏾‍♀️": "woman facepalming: medium-dark skin tone",
  "🤦🏾‍♀": "woman facepalming: medium-dark skin tone",
  "🤦🏿‍♀️": "woman facepalming: dark skin tone",
  "🤦🏿‍♀": "woman facepalming: dark skin tone",
  "🤷": "person shrugging",
  "🤷🏻": "person shrugging: light skin tone",
  "🤷🏼": "person shrugging: medium-light skin tone",
  "🤷🏽": "person shrugging: medium skin tone",
  "🤷🏾": "person shrugging: medium-dark skin tone",
  "🤷🏿": "person shrugging: dark skin tone",
  "🤷‍♂️": "man shrugging",
  "🤷‍♂": "man shrugging",
  "🤷🏻‍♂️": "man shrugging: light skin tone",
  "🤷🏻‍♂": "man shrugging: light skin tone",
  "🤷🏼‍♂️": "man shrugging: medium-light skin tone",
  "🤷🏼‍♂": "man shrugging: medium-light skin tone",
  "🤷🏽‍♂️": "man shrugging: medium skin tone",
  "🤷🏽‍♂": "man shrugging: medium skin tone",
  "🤷🏾‍♂️": "man shrugging: medium-dark skin tone",
  "🤷🏾‍♂": "man shrugging: medium-dark skin tone",
  "🤷🏿‍♂️": "man shrugging: dark skin tone",
  "🤷🏿‍♂": "man shrugging: dark skin tone",
  "🤷‍♀️": "woman shrugging",
  "🤷‍♀": "woman shrugging",
  "🤷🏻‍♀️": "woman shrugging: light skin tone",
  "🤷🏻‍♀": "woman shrugging: light skin tone",
  "🤷🏼‍♀️": "woman shrugging: medium-light skin tone",
  "🤷🏼‍♀": "woman shrugging: medium-light skin tone",
  "🤷🏽‍♀️": "woman shrugging: medium skin tone",
  "🤷🏽‍♀": "woman shrugging: medium skin tone",
  "🤷🏾‍♀️": "woman shrugging: medium-dark skin tone",
  "🤷🏾‍♀": "woman shrugging: medium-dark skin tone",
  "🤷🏿‍♀️": "woman shrugging: dark skin tone",
  "🤷🏿‍♀": "woman shrugging: dark skin tone",
  "👨‍⚕️": "man health worker",
  "👨‍⚕": "man health worker",
  "👨🏻‍⚕️": "man health worker: light skin tone",
  "👨🏻‍⚕": "man health worker: light skin tone",
  "👨🏼‍⚕️": "man health worker: medium-light skin tone",
  "👨🏼‍⚕": "man health worker: medium-light skin tone",
  "👨🏽‍⚕️": "man health worker: medium skin tone",
  "👨🏽‍⚕": "man health worker: medium skin tone",
  "👨🏾‍⚕️": "man health worker: medium-dark skin tone",
  "👨🏾‍⚕": "man health worker: medium-dark skin tone",
  "👨🏿‍⚕️": "man health worker: dark skin tone",
  "👨🏿‍⚕": "man health worker: dark skin tone",
  "👩‍⚕️": "woman health worker",
  "👩‍⚕": "woman health worker",
  "👩🏻‍⚕️": "woman health worker: light skin tone",
  "👩🏻‍⚕": "woman health worker: light skin tone",
  "👩🏼‍⚕️": "woman health worker: medium-light skin tone",
  "👩🏼‍⚕": "woman health worker: medium-light skin tone",
  "👩🏽‍⚕️": "woman health worker: medium skin tone",
  "👩🏽‍⚕": "woman health worker: medium skin tone",
  "👩🏾‍⚕️": "woman health worker: medium-dark skin tone",
  "👩🏾‍⚕": "woman health worker: medium-dark skin tone",
  "👩🏿‍⚕️": "woman health worker: dark skin tone",
  "👩🏿‍⚕": "woman health worker: dark skin tone",
  "👨‍🎓": "man student",
  "👨🏻‍🎓": "man student: light skin tone",
  "👨🏼‍🎓": "man student: medium-light skin tone",
  "👨🏽‍🎓": "man student: medium skin tone",
  "👨🏾‍🎓": "man student: medium-dark skin tone",
  "👨🏿‍🎓": "man student: dark skin tone",
  "👩‍🎓": "woman student",
  "👩🏻‍🎓": "woman student: light skin tone",
  "👩🏼‍🎓": "woman student: medium-light skin tone",
  "👩🏽‍🎓": "woman student: medium skin tone",
  "👩🏾‍🎓": "woman student: medium-dark skin tone",
  "👩🏿‍🎓": "woman student: dark skin tone",
  "👨‍🏫": "man teacher",
  "👨🏻‍🏫": "man teacher: light skin tone",
  "👨🏼‍🏫": "man teacher: medium-light skin tone",
  "👨🏽‍🏫": "man teacher: medium skin tone",
  "👨🏾‍🏫": "man teacher: medium-dark skin tone",
  "👨🏿‍🏫": "man teacher: dark skin tone",
  "👩‍🏫": "woman teacher",
  "👩🏻‍🏫": "woman teacher: light skin tone",
  "👩🏼‍🏫": "woman teacher: medium-light skin tone",
  "👩🏽‍🏫": "woman teacher: medium skin tone",
  "👩🏾‍🏫": "woman teacher: medium-dark skin tone",
  "👩🏿‍🏫": "woman teacher: dark skin tone",
  "👨‍⚖️": "man judge",
  "👨‍⚖": "man judge",
  "👨🏻‍⚖️": "man judge: light skin tone",
  "👨🏻‍⚖": "man judge: light skin tone",
  "👨🏼‍⚖️": "man judge: medium-light skin tone",
  "👨🏼‍⚖": "man judge: medium-light skin tone",
  "👨🏽‍⚖️": "man judge: medium skin tone",
  "👨🏽‍⚖": "man judge: medium skin tone",
  "👨🏾‍⚖️": "man judge: medium-dark skin tone",
  "👨🏾‍⚖": "man judge: medium-dark skin tone",
  "👨🏿‍⚖️": "man judge: dark skin tone",
  "👨🏿‍⚖": "man judge: dark skin tone",
  "👩‍⚖️": "woman judge",
  "👩‍⚖": "woman judge",
  "👩🏻‍⚖️": "woman judge: light skin tone",
  "👩🏻‍⚖": "woman judge: light skin tone",
  "👩🏼‍⚖️": "woman judge: medium-light skin tone",
  "👩🏼‍⚖": "woman judge: medium-light skin tone",
  "👩🏽‍⚖️": "woman judge: medium skin tone",
  "👩🏽‍⚖": "woman judge: medium skin tone",
  "👩🏾‍⚖️": "woman judge: medium-dark skin tone",
  "👩🏾‍⚖": "woman judge: medium-dark skin tone",
  "👩🏿‍⚖️": "woman judge: dark skin tone",
  "👩🏿‍⚖": "woman judge: dark skin tone",
  "👨🏻‍🌾": "man farmer: light skin tone",
  "👨🏼‍🌾": "man farmer: medium-light skin tone",
  "👨🏽‍🌾": "man farmer: medium skin tone",
  "👨🏾‍🌾": "man farmer: medium-dark skin tone",
  "👨🏿‍🌾": "man farmer: dark skin tone",
  "👩‍🌾": "woman farmer",
  "👩🏻‍🌾": "woman farmer: light skin tone",
  "👩🏼‍🌾": "woman farmer: medium-light skin tone",
  "👩🏽‍🌾": "woman farmer: medium skin tone",
  "👩🏾‍🌾": "woman farmer: medium-dark skin tone",
  "👩🏿‍🌾": "woman farmer: dark skin tone",
  "👨‍🍳": "man cook",
  "👨🏻‍🍳": "man cook: light skin tone",
  "👨🏼‍🍳": "man cook: medium-light skin tone",
  "👨🏽‍🍳": "man cook: medium skin tone",
  "👨🏾‍🍳": "man cook: medium-dark skin tone",
  "👨🏿‍🍳": "man cook: dark skin tone",
  "👩‍🍳": "woman cook",
  "👩🏻‍🍳": "woman cook: light skin tone",
  "👩🏼‍🍳": "woman cook: medium-light skin tone",
  "👩🏽‍🍳": "woman cook: medium skin tone",
  "👩🏾‍🍳": "woman cook: medium-dark skin tone",
  "👩🏿‍🍳": "woman cook: dark skin tone",
  "👨‍🔧": "man mechanic",
  "👨🏻‍🔧": "man mechanic: light skin tone",
  "👨🏼‍🔧": "man mechanic: medium-light skin tone",
  "👨🏽‍🔧": "man mechanic: medium skin tone",
  "👨🏾‍🔧": "man mechanic: medium-dark skin tone",
  "👨🏿‍🔧": "man mechanic: dark skin tone",
  "👩‍🔧": "woman mechanic",
  "👩🏻‍🔧": "woman mechanic: light skin tone",
  "👩🏼‍🔧": "woman mechanic: medium-light skin tone",
  "👩🏽‍🔧": "woman mechanic: medium skin tone",
  "👩🏾‍🔧": "woman mechanic: medium-dark skin tone",
  "👩🏿‍🔧": "woman mechanic: dark skin tone",
  "👨‍🏭": "man factory worker",
  "👨🏻‍🏭": "man factory worker: light skin tone",
  "👨🏼‍🏭": "man factory worker: medium-light skin tone",
  "👨🏽‍🏭": "man factory worker: medium skin tone",
  "👨🏾‍🏭": "man factory worker: medium-dark skin tone",
  "👨🏿‍🏭": "man factory worker: dark skin tone",
  "👩‍🏭": "woman factory worker",
  "👩🏻‍🏭": "woman factory worker: light skin tone",
  "👩🏼‍🏭": "woman factory worker: medium-light skin tone",
  "👩🏽‍🏭": "woman factory worker: medium skin tone",
  "👩🏾‍🏭": "woman factory worker: medium-dark skin tone",
  "👩🏿‍🏭": "woman factory worker: dark skin tone",
  "👨‍💼": "man office worker",
  "👨🏻‍💼": "man office worker: light skin tone",
  "👨🏼‍💼": "man office worker: medium-light skin tone",
  "👨🏽‍💼": "man office worker: medium skin tone",
  "👨🏾‍💼": "man office worker: medium-dark skin tone",
  "👨🏿‍💼": "man office worker: dark skin tone",
  "👩‍💼": "woman office worker",
  "👩🏻‍💼": "woman office worker: light skin tone",
  "👩🏼‍💼": "woman office worker: medium-light skin tone",
  "👩🏽‍💼": "woman office worker: medium skin tone",
  "👩🏾‍💼": "woman office worker: medium-dark skin tone",
  "👩🏿‍💼": "woman office worker: dark skin tone",
};
